const birim_kodu = [
  { ID: 'NIU', VALUE: 'ADET' },
  { ID: 'KGM', VALUE: 'KİLOGRAM' },
  { ID: 'KF', VALUE: 'KOLİ' },
  { ID: 'PA', VALUE: 'PAKET' },
  { ID: 'GRM', VALUE: 'GRAM' },
  { ID: 'LTR', VALUE: 'LİTRE' },
  { ID: 'MTR', VALUE: 'METRE' },
  { ID: 'MTK', VALUE: 'METRE KARE' },
  { ID: 'MTQ', VALUE: 'METRE KÜP' },
  { ID: 'DRL', VALUE: 'RULO' },
  { ID: '26', VALUE: 'TON' },
  { ID: 'SA', VALUE: 'ÇUVAL' },
  { ID: 'SL', VALUE: 'PALET' },
  { ID: 'SET', VALUE: 'TAKIM' },
  { ID: 'CT', VALUE: 'KARTON' },
  { ID: 'BX', VALUE: 'KUTU' },
  { ID: 'B32', VALUE: 'KG-METRE KARE' },
  { ID: 'CCT', VALUE: 'TON BAŞINA TAŞIMA KAPASİTESİ' },
  { ID: 'D30', VALUE: 'BRÜT KALORİ DEĞERİ' },
  { ID: 'D40', VALUE: 'BİN LİTRE' },
  { ID: 'GFI', VALUE: 'FISSILE İZOTOP GRAMI' },
  { ID: 'GT', VALUE: 'GROSS TON' },
  { ID: 'CEN', VALUE: 'YÜZ ADET' },
  { ID: 'KPO', VALUE: 'KİLOGRAM POTASYUM OKSİT' },
  { ID: 'MND', VALUE: 'KURUTULMUŞ NET AĞIRLIKLI KİLOGRAMI' },
  { ID: '3I', VALUE: 'KİLOGRAM-ADET' },
  { ID: 'KMA', VALUE: 'METİL AMİNLERİN KİLOGRAMI' },
  { ID: 'KNI', VALUE: 'AZOTUN KİLOGRAMI' },
  { ID: 'KPH', VALUE: 'Kg POTASYUM OKSİD' },
  { ID: 'KSD', VALUE: 'KURU ÜRÜN KİLOGRAMI %90' },
  { ID: 'KSH', VALUE: 'SODYUM HİDROKSİT KİLOGRAMI' },
  { ID: 'KUR', VALUE: 'URANYUM KİLOGRAMI' },
  { ID: 'KWH', VALUE: 'KİLOWATT SAAT' },
  { ID: 'KWT', VALUE: 'KİLOWATT' },
  { ID: 'LPA', VALUE: 'SAF ALKOL LİTRESİ' },
  { ID: 'NCL', VALUE: 'HÜCRE ADEDİ' },
  { ID: 'PR', VALUE: 'ÇİFT' },
  { ID: 'R9', VALUE: 'BİN METRE KÜP' },
  { ID: 'SET', VALUE: 'TAKIM' },
  { ID: 'T3', VALUE: 'BİN ADET' },
  { ID: 'C68', VALUE: 'PUNNET' },
  { ID: '4H', VALUE: 'P.CASES' },
  { ID: '5H', VALUE: 'C.BOXES' },
  { ID: 'BFT', VALUE: 'W.CASES' },
  { ID: 'EC', VALUE: 'P.BAG' },
  { ID: 'SA', VALUE: 'SACK' },
  { ID: 'BO', VALUE: 'ŞİŞE' },
  { ID: 'J57', VALUE: 'VARİL' },
  { ID: 'JOU', VALUE: 'VARDİYA' },
  { ID: 'MON', VALUE: 'AY' },
  { ID: 'HUR', VALUE: 'SAAT' },
  { ID: 'D62', VALUE: 'SANİYE' },
  { ID: 'ANN', VALUE: 'YIL' },
  { ID: 'DAY', VALUE: 'GÜN' },
  { ID: 'CL', VALUE: 'BOBİN' },
  { ID: 'E27', VALUE: 'DOZ' },
  { ID: 'EA', VALUE: 'EA' },
  { ID: 'J57', VALUE: 'VARİL' },
  { ID: 'PK', VALUE: 'PK' },
  { ID: 'ST', VALUE: 'TBK' },
  { ID: 'MGM', VALUE: 'MW' },
  { ID: 'DR', VALUE: 'BİDON' },
  { ID: '1J', VALUE: 'TON MİLE' },
  { ID: 'HAR', VALUE: 'HEKTAR' },
  { ID: 'LR', VALUE: 'TABAKA' },
  { ID: 'BJ', VALUE: 'KOVA' },
  { ID: 'KFO', VALUE: 'DİFOSFOR PENTAOKSİT KİLOGRAMI' },
  { ID: 'KHY', VALUE: 'HİDROJEN PEROKSİT KİLOGRAMI' },
  { ID: 'D32', VALUE: 'TERAWATT SAAT' },
  { ID: 'GWH', VALUE: 'GİGAWATT SAAT' },
  { ID: 'MWH', VALUE: 'MEGAWATT SAAT' },
  { ID: 'DMK', VALUE: 'DESİMETRE KARE' },
  { ID: 'SM3', VALUE: 'STANDART METREKÜP' },
  { ID: 'CTM', VALUE: 'KARAT' }
]

export default birim_kodu
