const paket_kodu = [
  { ID: 'TI', VALUE: '42 galonluk fıçı' },
  { ID: 'NT', VALUE: 'Ağ' },
  { ID: 'NV', VALUE: 'Ağ, boru, dokuma kumaş' },
  { ID: 'NU', VALUE: 'Ağ, boru, plastik' },
  { ID: 'CK', VALUE: 'Ahşap varil' },
  { ID: 'PK', VALUE: 'Ambalaj' },
  { ID: 'IE', VALUE: 'Ambalaj, gösterişli' },
  { ID: 'ID', VALUE: 'Ambalaj, gösterişli, metal' },
  { ID: 'IB', VALUE: 'Ambalaj, gösterişli, mukavva' },
  { ID: 'IC', VALUE: 'Ambalaj, gösterişli, plastik' },
  { ID: 'IA', VALUE: 'Ambalaj, gösterişli, tahta' },
  { ID: 'IF', VALUE: 'Ambalaj, kabarık' },
  { ID: 'IG', VALUE: 'Ambalaj, kağıt sarılı' },
  { ID: 'IK', VALUE: 'Ambalaj, mukavva, üstten tutmak için delikli' },
  { ID: 'AP', VALUE: 'Ampul, korumalı' },
  { ID: 'AM', VALUE: 'Ampul, korumasız' },
  { ID: 'VN', VALUE: 'Araç' },
  { ID: 'LE', VALUE: 'Bagaj' },
  { ID: 'CE', VALUE: 'Balık sepeti' },
  { ID: 'BP', VALUE: 'Balon, korumalı' },
  { ID: 'BF', VALUE: 'Balon, korumasız' },
  { ID: 'BN', VALUE: 'Balya, sıkıştırılmamış' },
  { ID: 'BL', VALUE: 'Balya, sıkıştırılmış' },
  { ID: 'SU', VALUE: 'Bavul' },
  { ID: '3A', VALUE: 'Beş galonluk bidon, çelik' },
  { ID: 'QL', VALUE: 'Beş galonluk bidon, çelik, çıkartılabilir kafa' },
  { ID: 'QK', VALUE: 'Beş galonluk bidon, çelik, çıkartılamayan kafa' },
  { ID: 'JC', VALUE: 'Beş galonluk bidon, dikdörtgen' },
  { ID: '3H', VALUE: 'Beş galonluk bidon, plastik' },
  { ID: 'QN', VALUE: 'Beş galonluk bidon, plastik, çıkartılabilir kafa' },
  { ID: 'QM', VALUE: 'Beş galonluk bidon, plastik, çıkartılamayan kafa' },
  { ID: 'JY', VALUE: 'Beş galonluk bidon, silindirik' },
  { ID: 'YR', VALUE: 'Birleşik ambalaj, alüminyum kasa içinde cam muhafaza' },
  { ID: 'YD', VALUE: 'Birleşik ambalaj, alüminyum kasa içinde plastik muhafaza' },
  { ID: 'YQ', VALUE: 'Birleşik ambalaj, alüminyum tambur içinde cam muhafaza' },
  { ID: 'YC', VALUE: 'Birleşik ambalaj, alüminyum tambur içinde plastik muhafaza' },
  { ID: '6P', VALUE: 'Birleşik ambalaj, cam muhafaza' },
  { ID: 'YB', VALUE: 'Birleşik ambalaj, çelik kasa kutu içinde plastik muhafaza' },
  { ID: 'YP', VALUE: 'Birleşik ambalaj, çelik sandık kutu içinde cam muhafaza' },
  { ID: 'YN', VALUE: 'Birleşik ambalaj, çelik tambur içinde cam muhafaza' },
  { ID: 'YA', VALUE: 'Birleşik ambalaj, çelik tambur içinde plastik muhafaza' },
  { ID: 'YY', VALUE: 'Birleşik ambalaj, dayanıklı olmayan plastik çıkın içinde cam muhafaza' },
  { ID: 'YW', VALUE: 'Birleşik ambalaj, elyaf tambur içinde cam muhafaza' },
  { ID: 'YJ', VALUE: 'Birleşik ambalaj, elyaf tambur içinde plastik muhafaza' },
  { ID: 'YV', VALUE: 'Birleşik ambalaj, hasır kapaklı sepet içinde cam muhafaza' },
  { ID: 'YH', VALUE: 'Birleşik ambalaj, kontrplak kutu içinde plastik muhafaza' },
  { ID: 'YT', VALUE: 'Birleşik ambalaj, kontrplak tambur içinde cam muhafaza' },
  { ID: 'YG', VALUE: 'Birleşik ambalaj, kontrplak tambur içinde plastik muhafaza' },
  { ID: '6H', VALUE: 'Birleşik ambalaj, plastik muhafaza' },
  { ID: 'YL', VALUE: 'Birleşik ambalaj, plastik tambur içinde plastik muhafaza' },
  { ID: 'YZ', VALUE: 'Birleşik ambalaj, sağlam plastik denk içinde cam muhafaza' },
  { ID: 'YM', VALUE: 'Birleşik ambalaj, sağlam plastik kutu içinde plastik muhafaza' },
  { ID: 'YX', VALUE: 'Birleşik ambalaj, sıkıştırılmış liflerden yapılmış tahta kutu içinde cam muhafaza' },
  { ID: 'YK', VALUE: 'Birleşik ambalaj, sıkıştırılmış liflerden yapılmış tahta kutu içinde plastik muhafaza' },
  { ID: 'YS', VALUE: 'Birleşik ambalaj, tahta kutu içinde cam muhafaza' },
  { ID: 'YF', VALUE: 'Birleşik ambalaj, tahtadan kutu içinde plastik muhafaza' },
  { ID: 'OK', VALUE: 'Blok' },
  { ID: 'BB', VALUE: 'Bobin' },
  { ID: 'SO', VALUE: 'Bobin' },
  { ID: 'BE', VALUE: 'Bohça' },
  { ID: '8C', VALUE: 'Bohça, tahta' },
  { ID: 'PI', VALUE: 'Boru' },
  { ID: 'PV', VALUE: 'Boru, tomar/deste/demet halinde' },
  { ID: 'TT', VALUE: 'Büyük el çantası' },
  { ID: 'TR', VALUE: 'Büyük eşya sandığı' },
  { ID: 'BU', VALUE: 'Büyük fıçı' },
  { ID: 'HG', VALUE: 'Büyük fıçı' },
  { ID: 'TO', VALUE: 'Büyük fıçı' },
  { ID: 'BT', VALUE: 'Cıvata' },
  { ID: 'CZ', VALUE: 'Çadır bezi' },
  { ID: 'BG', VALUE: 'Çanta' },
  { ID: 'JB', VALUE: 'Çanta, büyük boy' },
  { ID: 'MB', VALUE: 'Çanta, büyüyen' },
  { ID: '43', VALUE: 'Çanta, çok hacimli' },
  { ID: 'GY', VALUE: 'Çanta, çuval' },
  { ID: '5L', VALUE: 'Çanta, dokuma kumaş' },
  { ID: 'XF', VALUE: 'Çanta, dokuma kumaş, astarsız' },
  { ID: 'XG', VALUE: 'Çanta, dokuma kumaş, dayanaklı' },
  { ID: 'XH', VALUE: 'Çanta, dokuma kumaş, su geçirmez' },
  { ID: 'FX', VALUE: 'Çanta, esnek hazne' },
  { ID: 'ZB', VALUE: 'Çanta, geniş' },
  { ID: '5M', VALUE: 'Çanta, kağıt' },
  { ID: 'XJ', VALUE: 'Çanta, kağıt, katmanlı' },
  { ID: 'XK', VALUE: 'Çanta, kağıt, katmanlı, su geçirmez' },
  { ID: 'EC', VALUE: 'Çanta, plastik' },
  { ID: '5H', VALUE: 'Çanta, plastik dokuma' },
  { ID: 'XA', VALUE: 'Çanta, plastik dokuma, astarsız' },
  { ID: 'XB', VALUE: 'Çanta, plastik dokuma, dayanaklı' },
  { ID: 'XC', VALUE: 'Çanta, plastik dokuma, su geçirmez' },
  { ID: 'XD', VALUE: 'Çanta, plastik tabakalı' },
  { ID: '44', VALUE: 'Çanta, şeffaf plastik' },
  { ID: 'TC', VALUE: 'Çay sandığı' },
  { ID: 'SW', VALUE: 'Çekme-sarma' },
  { ID: 'FR', VALUE: 'Çerçeve' },
  { ID: 'PT', VALUE: 'Çömlek' },
  { ID: 'BR', VALUE: 'Çubuk' },
  { ID: 'RD', VALUE: 'Çubuk' },
  { ID: 'BZ', VALUE: 'Çubuk, tomar/deste/demet halinde' },
  { ID: 'RZ', VALUE: 'Çubuk, tomar/deste/demet halinde' },
  { ID: 'SA', VALUE: 'Çuval' },
  { ID: 'MS', VALUE: 'Çuval, çok katmanlı' },
  { ID: 'CP', VALUE: 'Damacana, korumalı' },
  { ID: 'DP', VALUE: 'Damacana, korumalı' },
  { ID: 'CO', VALUE: 'Damacana, korumasız' },
  { ID: 'DJ', VALUE: 'Damacana, korumasız' },
  { ID: 'FL', VALUE: 'Dar küçük şişe' },
  { ID: 'DR', VALUE: 'Davul' },
  { ID: '1B', VALUE: 'Davul, alüminyum' },
  { ID: 'QD', VALUE: 'Davul, alüminyum, çıkartılabilir kafa' },
  { ID: 'QC', VALUE: 'Davul, alüminyum, çıkartılamayan kafa' },
  { ID: '1A', VALUE: 'Davul, çelik' },
  { ID: 'QB', VALUE: 'Davul, çelik, çıkartılabilir kafa' },
  { ID: 'QA', VALUE: 'Davul, çelik, çıkartılamayan kafa' },
  { ID: 'DI', VALUE: 'Davul, demir' },
  { ID: '1G', VALUE: 'Davul, elyaf' },
  { ID: '1D', VALUE: 'Davul, kontrplak' },
  { ID: 'IH', VALUE: 'Davul, plastik' },
  { ID: 'QG', VALUE: 'Davul, plastik, çıkartılabilir kafa' },
  { ID: 'QF', VALUE: 'Davul, plastik, çıkartılamayan kafa' },
  { ID: '1W', VALUE: 'Davul, tahta' },
  { ID: 'TS', VALUE: 'Demet' },
  { ID: 'BH', VALUE: 'Deste' },
  { ID: 'GI', VALUE: 'Direk' },
  { ID: 'GZ', VALUE: 'Direk, tomar/deste/demet halinde' },
  { ID: 'DN', VALUE: 'Dispenser' },
  { ID: 'VG', VALUE: 'Dökme, gaz (1031 mbar ve 15oC’de)' },
  { ID: 'VS', VALUE: 'Dökme, hurda metal' },
  { ID: 'VO', VALUE: 'Dökme, katı, büyük parçacıklar (yumrular)' },
  { ID: 'VR', VALUE: 'Dökme, katı, granüllü parçacıklar (tahıllar)' },
  { ID: 'VY', VALUE: 'Dökme, katı, ince parçacıklar (toz)' },
  { ID: 'VL', VALUE: 'Dökme, sıvı' },
  { ID: 'VQ', VALUE: 'Dökme, sıvılaştırılmış gaz (normal olmayan ısı/basınçta)' },
  { ID: 'NA', VALUE: 'Elde mevcut olmayan' },
  { ID: 'FB', VALUE: 'Esnek çanta' },
  { ID: 'FE', VALUE: 'Esnek tank' },
  { ID: 'SX', VALUE: 'Fide' },
  { ID: 'FP', VALUE: 'Film paketi' },
  { ID: 'CU', VALUE: 'Fincan' },
  { ID: 'FT', VALUE: 'Foodtainer' },
  { ID: 'VK', VALUE: 'Furgon ambalajı' },
  { ID: 'SE', VALUE: 'Gemici sandığı' },
  { ID: 'PL', VALUE: 'Gerdel' },
  { ID: 'RG', VALUE: 'Halka' },
  { ID: 'MT', VALUE: 'Hasır' },
  { ID: 'PH', VALUE: 'İbrik' },
  { ID: 'SD', VALUE: 'İğ' },
  { ID: 'JT', VALUE: 'Jüt çuval' },
  { ID: 'CG', VALUE: 'Kafes' },
  { ID: 'RK', VALUE: 'Kafes' },
  { ID: 'RJ', VALUE: 'Kafes, çengelli' },
  { ID: 'DG', VALUE: 'Kafes, Milletler Topluluğu Elleçleme Ekipman Havuzu (CHEP)' },
  { ID: 'CW', VALUE: 'Kafes, rulo' },
  { ID: 'UC', VALUE: 'Kafesli olmayan' },
  { ID: 'PN', VALUE: 'Kalas' },
  { ID: 'PZ', VALUE: 'Kalas, tomar/deste/demet halinde' },
  { ID: 'HN', VALUE: 'Kanca' },
  { ID: 'CL', VALUE: 'Kangal' },
  { ID: 'BI', VALUE: 'Kap' },
  { ID: 'HR', VALUE: 'Kapaklı sepet' },
  { ID: 'NE', VALUE: 'Kapsız veya ambalajlanmamış' },
  { ID: 'NG', VALUE: 'Kapsız veya ambalajlanmamış, çoklu birim' },
  { ID: 'NF', VALUE: 'Kapsız veya ambalajlanmamış, tek birim' },
  { ID: 'AV', VALUE: 'Kapsül' },
  { ID: 'CT', VALUE: 'Karton' },
  { ID: 'CQ', VALUE: 'Kartuş' },
  { ID: 'CS', VALUE: 'Kasa' },
  { ID: 'CB', VALUE: 'Kasa, bira' },
  { ID: 'SS', VALUE: 'Kasa, çelik' },
  { ID: 'FD', VALUE: 'Kasa, çerçeveli' },
  { ID: 'DC', VALUE: 'Kasa, çok katmanlı, mukavva' },
  { ID: 'DA', VALUE: 'Kasa, çok katmanlı, plastik' },
  { ID: 'DB', VALUE: 'Kasa, çok katmanlı, tahta' },
  { ID: 'DK', VALUE: 'Kasa, hacimli, mukavva' },
  { ID: 'DL', VALUE: 'Kasa, hacimli, plastik' },
  { ID: 'DM', VALUE: 'Kasa, hacimli, tahta' },
  { ID: '7A', VALUE: 'Kasa, hareketli' },
  { ID: 'SK', VALUE: 'Kasa, iskeletli' },
  { ID: 'EI', VALUE: 'Kasa, izotermik' },
  { ID: 'MA', VALUE: 'Kasa, metal' },
  { ID: 'FC', VALUE: 'Kasa, meyve' },
  { ID: 'ED', VALUE: 'Kasa, palet tabanlı' },
  { ID: 'EH', VALUE: 'Kasa, palet tabanlı, metal' },
  { ID: 'EF', VALUE: 'Kasa, palet tabanlı, mukavva' },
  { ID: 'EG', VALUE: 'Kasa, palet tabanlı, plastik' },
  { ID: 'EE', VALUE: 'Kasa, palet tabanlı, tahtadan' },
  { ID: 'SC', VALUE: 'Kasa, sığ' },
  { ID: 'MC', VALUE: 'Kasa, süt' },
  { ID: '7B', VALUE: 'Kasa, tahta' },
  { ID: '8B', VALUE: 'Kasa, tahta' },
  { ID: 'JR', VALUE: 'Kavanoz' },
  { ID: 'B4', VALUE: 'Kayış' },
  { ID: 'PO', VALUE: 'Kese' },
  { ID: 'CV', VALUE: 'Kılıf' },
  { ID: 'SI', VALUE: 'Kızak' },
  { ID: 'MX', VALUE: 'Kibrit kutusu' },
  { ID: 'SH', VALUE: 'Koku torbası' },
  { ID: 'OU', VALUE: 'Konteyner, dış' },
  { ID: '1F', VALUE: 'Konteyner, esnek' },
  { ID: 'GL', VALUE: 'Konteyner, galon' },
  { ID: 'ME', VALUE: 'Konteyner, metal' },
  { ID: 'CN', VALUE: 'Konteyner, taşıma ekipmanı olarak başka şekilde belirtilmedikçe' },
  { ID: 'BJ', VALUE: 'Kova' },
  { ID: 'BX', VALUE: 'Kutu' },
  { ID: '4B', VALUE: 'Kutu, alüminyum' },
  { ID: '4A', VALUE: 'Kutu, çelik' },
  { ID: '4C', VALUE: 'Kutu, doğal tahta' },
  { ID: '4D', VALUE: 'Kutu, kontrplak' },
  { ID: 'DH', VALUE: 'Kutu, Milletler Topluluğu Elleçleme Ekipman Havuzu (CHEP), Eurobox' },
  { ID: '4H', VALUE: 'Kutu, plastik' },
  { ID: 'QR', VALUE: 'Kutu, plastik, genişletilmiş' },
  { ID: 'QS', VALUE: 'Kutu, plastik, sağlam' },
  { ID: '4G', VALUE: 'Kutu, sıkılaştırılmış liflerden yapılmış tahta' },
  { ID: 'BW', VALUE: 'Kutu, sıvılar için' },
  { ID: 'QP', VALUE: 'Kutu, tahtadan, doğal tahta, basit' },
  { ID: 'QQ', VALUE: 'Kutu, tahtadan, doğal tahta, dayanıklı dış yüzey' },
  { ID: '4F', VALUE: 'Kutu, yeniden düzenlenmiş tahta' },
  { ID: 'KG', VALUE: 'Küçük fıçı' },
  { ID: 'FO', VALUE: 'Küçük sandık' },
  { ID: 'AJ', VALUE: 'Külah' },
  { ID: 'IN', VALUE: 'Külçe' },
  { ID: 'IZ', VALUE: 'Külçe, tomar/deste/demet halinde' },
  { ID: 'AL', VALUE: 'Küre' },
  { ID: 'LG', VALUE: 'Kütük' },
  { ID: 'LZ', VALUE: 'Kütük, tomar/deste/demet halinde' },
  { ID: 'BM', VALUE: 'Leğen' },
  { ID: 'SB', VALUE: 'Levha' },
  { ID: 'LV', VALUE: 'Liftvan' },
  { ID: 'RL', VALUE: 'Makara' },
  { ID: 'CM', VALUE: 'Mukavva' },
  { ID: 'WA', VALUE: 'Orta boy büyüklükte konteyner' },
  { ID: 'WD', VALUE: 'Orta boy büyüklükte konteyner, alüminyum' },
  { ID: 'WH', VALUE: 'Orta boy büyüklükte konteyner, alüminyum, basınçlı > 10 kpa' },
  { ID: 'WL', VALUE: 'Orta boy büyüklükte konteyner, alüminyum, sıvı' },
  { ID: 'ZS', VALUE: 'Orta boy büyüklükte konteyner, bileşik' },
  { ID: 'ZP', VALUE: 'Orta boy büyüklükte konteyner, bileşik, esnek plastik, basınçlı' },
  { ID: 'ZM', VALUE: 'Orta boy büyüklükte konteyner, bileşik, esnek plastik, sağlam' },
  { ID: 'ZR', VALUE: 'Orta boy büyüklükte konteyner, bileşik, esnek plastik, sıvı' },
  { ID: 'ZN', VALUE: 'Orta boy büyüklükte konteyner, bileşik, sert plastik, basınçlı' },
  { ID: 'ZL', VALUE: 'Orta boy büyüklükte konteyner, bileşik, sert plastik, sağlam' },
  { ID: 'ZQ', VALUE: 'Orta boy büyüklükte konteyner, bileşik, sert plastik, sıvı' },
  { ID: 'WC', VALUE: 'Orta boy büyüklükte konteyner, çelik' },
  { ID: 'WG', VALUE: 'Orta boy büyüklükte konteyner, çelik, basınçlı > 10 kpa' },
  { ID: 'WK', VALUE: 'Orta boy büyüklükte konteyner, çelik, sıvı' },
  { ID: 'WT', VALUE: 'Orta boy büyüklükte konteyner, dış astarlı dokuma kumaş' },
  { ID: 'ZW', VALUE: 'Orta boy büyüklükte konteyner, doğal tahta' },
  { ID: 'WU', VALUE: 'Orta boy büyüklükte konteyner, doğal tahta, astarlı' },
  { ID: 'WW', VALUE: 'Orta boy büyüklükte konteyner, dokuma kumaş, astarlı' },
  { ID: 'WV', VALUE: 'Orta boy büyüklükte konteyner, dokuma kumaş, kaplamalı' },
  { ID: 'WX', VALUE: 'Orta boy büyüklükte konteyner, dokuma kumaş, kaplamalı ve astarlı' },
  { ID: 'ZU', VALUE: 'Orta boy büyüklükte konteyner, esnek' },
  { ID: 'ZA', VALUE: 'Orta boy büyüklükte konteyner, kağıt, çok katmanlı' },
  { ID: 'ZC', VALUE: 'Orta boy büyüklükte konteyner, kağıt, çok katmanlı, su geçirmez' },
  { ID: 'WF', VALUE: 'Orta boy büyüklükte konteyner, metal' },
  { ID: 'WJ', VALUE: 'Orta boy büyüklükte konteyner, metal, basınç 10 kpa' },
  { ID: 'ZV', VALUE: 'Orta boy büyüklükte konteyner, metal, çelik dışında' },
  { ID: 'WM', VALUE: 'Orta boy büyüklükte konteyner, metal, sıvı' },
  { ID: 'WQ', VALUE: 'Orta boy büyüklükte konteyner, örme plastik, astarlı' },
  { ID: 'WP', VALUE: 'Orta boy büyüklükte konteyner, örme plastik, kaplamalı' },
  { ID: 'WR', VALUE: 'Orta boy büyüklükte konteyner, örme plastik, kaplamalı ve astarlı' },
  { ID: 'WN', VALUE: 'Orta boy büyüklükte konteyner, örme plastik, kaplamalı ve astarlı olmayan' },
  { ID: 'WS', VALUE: 'Orta boy büyüklükte konteyner, plastik film' },
  { ID: 'AA', VALUE: 'Orta boy büyüklükte konteyner, sert plastik' },
  { ID: 'ZH', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, müstakil, basınçlı' },
  { ID: 'ZF', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, müstakil, sağlam' },
  { ID: 'ZK', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, müstakil, sıvı' },
  { ID: 'ZG', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, teçhizatlı, basınçlı' },
  { ID: 'ZD', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, teçhizatlı, sağlam' },
  { ID: 'ZJ', VALUE: 'Orta boy büyüklükte konteyner, sert plastik, teçhizatlı, sıvı' },
  { ID: 'ZT', VALUE: 'Orta boy büyüklükte konteyner, sıkıştırılmış liflerden yapılmış tahta' },
  { ID: 'ZX', VALUE: 'Orta boy büyüklükte konteyner, sıkıştırılmış liflerden yapılmış tahta, kaplamalı' },
  { ID: 'ZB', VALUE: 'Orta boy büyüklükte konteyner, sıkıştırılmış liflerden yapılmış tahta, astarlı' },
  { ID: 'ZY', VALUE: 'Orta boy büyüklükte konteyner, sıkıştırılmış liflerden yapılmış tahta, kaplamalı ve astarlı' },
  { ID: 'ZL', VALUE: 'Orta boy büyüklükte konteyner, yassı, teçhizatlı, basınçlı' },
  { ID: 'YH', VALUE: 'Orta boy büyüklükte konteyner, yassı, teçhizatlı, sağlam' },
  { ID: 'YB', VALUE: 'Orta boy büyüklükte konteyner, yassı, teçhizatlı, sıvı' },
  { ID: 'YJ', VALUE: 'Orta boy büyüklükte konteyner, yassı, teçhizatlı, başka türlü belirtilmedikçe' },
  { ID: 'YF', VALUE: 'Orta boy büyüklükte konteyner, yassı, sıkıştırılmış liflerden yapılmış tahta' },
  { ID: 'YQ', VALUE: 'Orta boy büyüklükte konteyner, yassı, sıkıştırılmış liflerden yapılmış tahta, kaplamalı' },
  { ID: 'YI', VALUE: 'Orta boy büyüklükte konteyner, yassı, sıkıştırılmış liflerden yapılmış tahta, astarlı' },
  {
    ID: 'YP',
    VALUE: 'Orta boy büyüklükte konteyner, yassı, sıkıştırılmış liflerden yapılmış tahta, kaplamalı ve astarlı'
  },
  { ID: 'ZA', VALUE: 'Orta boy büyüklükte konteyner, yassı, başka türlü belirtilmedikçe' },
  { ID: 'ZV', VALUE: 'Orta boy büyüklükte konteyner, başka türlü belirtilmedikçe' },
  { ID: 'ZY', VALUE: 'Orta boy büyüklükte konteyner, başka türlü belirtilmedikçe' },
  { ID: 'ZZ', VALUE: 'Orta boy büyüklükte konteyner, başka türlü belirtilmedikçe' },
  { ID: 'AA', VALUE: 'Orta boy büyüklükte konteyner, başka türlü belirtilmedikçe' },
  { ID: 'ZZ', VALUE: 'Orta boy büyüklükte konteyner, başka türlü belirtilmedikçe' },
  { ID: 'BW', VALUE: 'Büyük konteyner, çelik' },
  { ID: 'BX', VALUE: 'Büyük konteyner, doğal tahta' },
  { ID: 'BQ', VALUE: 'Büyük konteyner, doğal tahta, kaplamalı' },
  { ID: 'BR', VALUE: 'Büyük konteyner, doğal tahta, astarlı' },
  { ID: 'BT', VALUE: 'Büyük konteyner, doğal tahta, kaplamalı ve astarlı' },
  { ID: 'BS', VALUE: 'Büyük konteyner, doğal tahta, başka türlü belirtilmedikçe' },
  { ID: 'BCA', VALUE: 'Büyük konteyner, başka türlü belirtilmedikçe' },
  { ID: 'BCB', VALUE: 'Büyük konteyner, başka türlü belirtilmedikçe' }
]

export default paket_kodu
